use_frameworks!

target 'HSegmentControl_Example' do
  pod 'HSegmentControl', :path => '../'

  target 'HSegmentControl_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
